# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(767, 654)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 60, 160, 531))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.btn_ok = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ok.setGeometry(QtCore.QRect(20, 7, 161, 41))
        self.btn_ok.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"border-color: rgb(85, 255, 127);")
        self.btn_ok.setObjectName("btn_ok")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 60, 551, 471))
        self.label.setText("")
        self.label.setObjectName("label")
        self.btn_left = QtWidgets.QPushButton(self.centralwidget)
        self.btn_left.setGeometry(QtCore.QRect(210, 10, 121, 41))
        self.btn_left.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.btn_left.setObjectName("btn_left")
        self.btn_right = QtWidgets.QPushButton(self.centralwidget)
        self.btn_right.setGeometry(QtCore.QRect(350, 10, 121, 41))
        self.btn_right.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.btn_right.setObjectName("btn_right")
        self.btn_up = QtWidgets.QPushButton(self.centralwidget)
        self.btn_up.setGeometry(QtCore.QRect(490, 10, 121, 41))
        self.btn_up.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.btn_up.setObjectName("btn_up")
        self.btn_flip = QtWidgets.QPushButton(self.centralwidget)
        self.btn_flip.setGeometry(QtCore.QRect(630, 10, 121, 41))
        self.btn_flip.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.btn_flip.setObjectName("btn_flip")
        self.btn_resise = QtWidgets.QPushButton(self.centralwidget)
        self.btn_resise.setGeometry(QtCore.QRect(210, 550, 151, 41))
        self.btn_resise.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.btn_resise.setObjectName("btn_resise")
        self.btn_sharp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sharp.setGeometry(QtCore.QRect(380, 550, 171, 41))
        self.btn_sharp.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.btn_sharp.setObjectName("btn_sharp")
        self.btn_bw = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bw.setGeometry(QtCore.QRect(570, 550, 181, 41))
        self.btn_bw.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.btn_bw.setObjectName("btn_bw")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 767, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_ok.setText(_translate("MainWindow", "Open folder"))
        self.btn_left.setText(_translate("MainWindow", "left"))
        self.btn_right.setText(_translate("MainWindow", "right"))
        self.btn_up.setText(_translate("MainWindow", "up"))
        self.btn_flip.setText(_translate("MainWindow", "flip"))
        self.btn_resise.setText(_translate("MainWindow", "resise"))
        self.btn_sharp.setText(_translate("MainWindow", "sharp"))
        self.btn_bw.setText(_translate("MainWindow", "B/W"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
